ALTER TABLE `contract` ADD COLUMN `manager_id` varchar(64);
ALTER TABLE `contract` ADD COLUMN `warning_days` int;
ALTER TABLE `contract` ADD COLUMN `warning_enabled` tinyint;
ALTER TABLE `contract` ADD COLUMN `last_warning_time` datetime;
ALTER TABLE `contract` ADD COLUMN `warning_count` int;
ALTER TABLE `contract` ADD INDEX `idx_contract_manager_id` (`manager_id`);
ALTER TABLE `contract` ADD INDEX `idx_contract_expiry_date` (`expiry_date`);
ALTER TABLE `contract` ADD INDEX `idx_contract_warning_enabled` (`warning_enabled`);
ALTER TABLE `contract` ADD INDEX `idx_contract_status` (`status`);
ALTER TABLE `management_system_material_item` ADD COLUMN `system_name` varchar(255);
ALTER TABLE `management_system_material_item` ADD COLUMN `system_code` varchar(255);
ALTER TABLE `management_system_material_item` ADD COLUMN `material_item_name` varchar(255);
ALTER TABLE `management_system_material_item` ADD INDEX `idx_system_code` (`system_code`);
ALTER TABLE `management_system_material_item` ADD INDEX `idx_material_item_name` (`material_item_name`);
ALTER TABLE `material_item` DROP COLUMN `material_id`;
ALTER TABLE `material_item` DROP COLUMN `material_name`;
ALTER TABLE `material_item` ADD COLUMN `material_item_id` bigint;
ALTER TABLE `material_item` ADD COLUMN `material_item_name` varchar(255);
ALTER TABLE `material_item` ADD COLUMN `material_type` varchar(50);
ALTER TABLE `material_item` ADD INDEX `idx_material_item_type` (`material_type`);
ALTER TABLE `person` MODIFY COLUMN `user_status` varchar(10) NOT NULL DEFAULT '启用';
ALTER TABLE `policy` DROP COLUMN `department_id`;
ALTER TABLE `policy` DROP COLUMN `department_name`;
ALTER TABLE `policy` DROP COLUMN `personnel_scope`;
ALTER TABLE `policy` DROP COLUMN `related_personnel`;
ALTER TABLE `policy` DROP COLUMN `material_item_count`;
ALTER TABLE `policy` DROP COLUMN `material_item_names`;
ALTER TABLE `policy` ADD COLUMN `is_public` tinyint;
ALTER TABLE `policy` ADD COLUMN `publish_department_id` varchar(100);
ALTER TABLE `policy` ADD COLUMN `publish_department_name` varchar(255);
ALTER TABLE `policy` ADD COLUMN `version_number` varchar(20);
ALTER TABLE `policy` ADD INDEX `idx_publish_department_id` (`publish_department_id`);
ALTER TABLE `policy` DROP INDEX `idx_department_id`;
ALTER TABLE `policy` DROP INDEX `idx_material_item_count`;
ALTER TABLE `position` DROP COLUMN `create_time`;
ALTER TABLE `position` DROP COLUMN `update_time`;
ALTER TABLE `position` MODIFY COLUMN `position_type` varchar(36) NULL;
ALTER TABLE `position` MODIFY COLUMN `position_level` varchar(36) NULL;
ALTER TABLE `position` MODIFY COLUMN `authorized_strength` int NULL DEFAULT '1';
ALTER TABLE `position` MODIFY COLUMN `sort_order` int NULL DEFAULT '0';
ALTER TABLE `position` ADD COLUMN `created_time` datetime;
ALTER TABLE `position` ADD COLUMN `updated_time` datetime;
ALTER TABLE `position` ADD COLUMN `position_leader_id` varchar(50);
ALTER TABLE `position` ADD COLUMN `position_responsibilities` text;
ALTER TABLE `position` ADD COLUMN `position_requirements` text;
ALTER TABLE `position` ADD COLUMN `created_by` varchar(36);
ALTER TABLE `position` ADD COLUMN `updated_by` varchar(36);